# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

# [1]: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent

trigger:
- master 

pool:
  vmImage: 'windows-latest' # All. Microsoft-hosted agent [1]

stages:
-stage: Ghislain Stage
 displayName: Ghislain first Stage
  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
  jobs:
    -job: GhislainJob
    displayName: Ghislain Second Job
     steps:
     - task: NuGetToolInstaller@1
     - task: NuGetCommand@2
       inputs:
       restoreSolution: '$(solution)'
     - task: VSBuild@1
       inputs:
       solution: '$(solution)'
       platform: '$(buildPlatform)'
       configuration: '$(buildConfiguration)'
     - task: VSTest@2
       inputs:
       platform: '$(buildPlatform)'
       configuration: '$(buildConfiguration)'
