# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

# [1]: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent

# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  - master

pool:
  vmImage: "windows-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: "Install .net core 3.0 (preview)"
    inputs:
      packageType: sdk
      version: "3.0.100-preview6-012264"
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet restore

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: "**/*.csproj"
      arguments: "--configuration Release"
      verbosityRestore: "Detailed"

  - task: VSTest@2
    inputs:
      platform: "$(buildPlatform)"
      configuration: "$(buildConfiguration)"

  - task: NugetCommand@2
    displayName: "Nuget packae PackCommandGhislain"
    inputs:
      command: "pack"
      packagesToPack: "**/*.csproj"
      packDestination: "$(Build.ArtifactStagingDirectory)"
